name: lit
description: "LIT - Life. Improved. Together."

publish_to: 'none'

version: 0.3.21+19

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- Pacotes do Projeto ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.3
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.7  
  cupertino_icons: ^1.0.6
  
  # --- Notificações ---
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.3
  intl: ^0.19.0

  # --- Import/Export ---
  file_picker: ^10.0.0
  permission_handler: ^12.0.0
  device_info_plus: ^12.2.0
  app_settings: ^6.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/icon.png

